// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL3hKmOELoYhJZKUxj_wxHMoZdbfP5z-Q',
    appId: '1:527892939651:web:e87e1e35e9060115072cb6',
    messagingSenderId: '527892939651',
    projectId: 'cafeconnect-b64da',
    authDomain: 'cafeconnect-b64da.firebaseapp.com',
    storageBucket: 'cafeconnect-b64da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvkbQS_rZl3K1nLLpUki0Uw6PSvTdwO3g',
    appId: '1:527892939651:android:f026883529741fe4072cb6',
    messagingSenderId: '527892939651',
    projectId: 'cafeconnect-b64da',
    storageBucket: 'cafeconnect-b64da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_SqLLHoGpSgdNU9hIz9Po3rO51c_s3s',
    appId: '1:527892939651:ios:cb8b3456eb02f083072cb6',
    messagingSenderId: '527892939651',
    projectId: 'cafeconnect-b64da',
    storageBucket: 'cafeconnect-b64da.appspot.com',
    iosClientId: '527892939651-j5cr7umlimbeod3iqclql6n8aerjg9t0.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8_SqLLHoGpSgdNU9hIz9Po3rO51c_s3s',
    appId: '1:527892939651:ios:1a99a8496bcb6694072cb6',
    messagingSenderId: '527892939651',
    projectId: 'cafeconnect-b64da',
    storageBucket: 'cafeconnect-b64da.appspot.com',
    iosClientId: '527892939651-panhtq6g5bei6d9jon9bo20o511tfc7e.apps.googleusercontent.com',
    iosBundleId: 'com.example.cafeconnect.RunnerTests',
  );
}
